const express = require('express')
const authRoutes = require('./auth')
const customerRoutes = require('./customers')
const vehicleRoutes = require('./vehicles')
const serviceRoutes = require('./services')
const salesRoutes = require('./sales')
const paymentRoutes = require('./payments')
const appointmentRoutes = require('./appointments')
const reportRoutes = require('./reports')
const adminRoutes = require('./admin')
const exportRoutes = require('./exports')
const overpaymentRoutes = require('./overpayments')
const quotationRoutes = require('./quotations')
const jobOrderRoutes = require('./joborders')
const inventoryRoutes = require('./inventory')
const commissionRoutes = require('./commissions')
const vehicleMakeRoutes = require('./vehicleMakes')
const configRoutes = require('./configRoutes')
const emailCampaignRoutes = require('./emailCampaigns')
const promoCodeRoutes = require('./promoCodes')
const onlineQuotationRequestRoutes = require('./onlineQuotationRequests')
const subscriptionRoutes = require('./subscriptions')
const pmsRoutes = require('./pms')
const settingsRoutes = require('./settings')
const notificationsRoutes = require('./notifications')
const landingChatRoutes = require('./landingChat')
const { requireAuth, enforceAdminAccessPolicy } = require('../middleware/auth')

const router = express.Router()

router.use('/auth', authRoutes)
router.use('/config', configRoutes)
router.use('/settings', settingsRoutes)
router.use('/notifications', notificationsRoutes)
router.use(requireAuth)
router.use(enforceAdminAccessPolicy)
router.use('/customers', customerRoutes)
router.use('/vehicles', vehicleRoutes)
router.use('/services', serviceRoutes)
router.use('/sales', salesRoutes)
router.use('/payments', paymentRoutes)
router.use('/appointments', appointmentRoutes)
router.use('/reports', reportRoutes)
router.use('/admin', adminRoutes)
router.use('/exports', exportRoutes)
router.use('/overpayments', overpaymentRoutes)
router.use('/quotations', quotationRoutes)
router.use('/job-orders', jobOrderRoutes)
router.use('/inventory', inventoryRoutes)
router.use('/commissions', commissionRoutes)
router.use('/vehicle-makes', vehicleMakeRoutes)
router.use('/email-campaigns', emailCampaignRoutes)
router.use('/promo-codes', promoCodeRoutes)
router.use('/online-quotation-requests', onlineQuotationRequestRoutes)
router.use('/subscriptions', subscriptionRoutes)
router.use('/pms', pmsRoutes)
router.use('/landing-chat', landingChatRoutes)

module.exports = router

